name: BoxPvP full build lifecycle

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Install xargs
        run: sudo apt-get update && sudo apt-get install -y findutils

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradle build lifecycle
        run: ./gradlew build shadowJar --no-daemon

      - name: Upload plugin file
        uses: actions/upload-artifact@v2
        with:
          name: BoxPvP
          path: build/libs/BoxPvP-latest.jar
